import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App.js";
import "./styles.css";
import "./social.css";
import "./cozy.css";
import "./cozy-fixes.css";
import "./cozy-polish.css";
import "./cozy-fit.css";
import "./cozy-cute.css";
import "./analytics.css";
import "./stats-polish.css";
import "./curated.css";
import "./profile-input.css";
import "./artwork-fallback.css";
import "./ui-alignment.css";
import "./playful-polish.css";
import "./library-controls.css";
import "./custom-shelves.css";
createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
